# 配置文件
# cookie 以实际获取为准，如遇到带双引号的需用 \ 转义，或改为单引号，或将最外层双引号改为单引号
# e.g.1 cookie = "xxx; app_param={\"brand\":\"iPhone\"}"
# e.g.2 cookie = "xxx; app_param={'brand':'iPhone'}"
# e.g.3 cookie = 'xxx; app_param={"brand":"iPhone"}'

# LeetCode 每日一题
LEETCODE = false
# 每日一句
MOTTO = true
# 每日新闻
NEWS = false

# GLaDOS【WEB】
# https://glados.network cookie
[[GLADOS]]
cookie = ""